//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: usermgmt/usermgmt.proto

package usermgmt;

@kotlin.jvm.JvmSynthetic
public inline fun getUsersParams(block: usermgmt.GetUsersParamsKt.Dsl.() -> kotlin.Unit): usermgmt.Usermgmt.GetUsersParams =
  usermgmt.GetUsersParamsKt.Dsl._create(usermgmt.Usermgmt.GetUsersParams.newBuilder()).apply { block() }._build()
public object GetUsersParamsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: usermgmt.Usermgmt.GetUsersParams.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: usermgmt.Usermgmt.GetUsersParams.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): usermgmt.Usermgmt.GetUsersParams = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun usermgmt.Usermgmt.GetUsersParams.copy(block: usermgmt.GetUsersParamsKt.Dsl.() -> kotlin.Unit): usermgmt.Usermgmt.GetUsersParams =
  usermgmt.GetUsersParamsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
