//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: usermgmt/usermgmt.proto

package usermgmt;

@kotlin.jvm.JvmSynthetic
public inline fun user(block: usermgmt.UserKt.Dsl.() -> kotlin.Unit): usermgmt.Usermgmt.User =
  usermgmt.UserKt.Dsl._create(usermgmt.Usermgmt.User.newBuilder()).apply { block() }._build()
public object UserKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: usermgmt.Usermgmt.User.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: usermgmt.Usermgmt.User.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): usermgmt.Usermgmt.User = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>int32 age = 2;</code>
     */
    public var age: kotlin.Int
      @JvmName("getAge")
      get() = _builder.getAge()
      @JvmName("setAge")
      set(value) {
        _builder.setAge(value)
      }
    /**
     * <code>int32 age = 2;</code>
     */
    public fun clearAge() {
      _builder.clearAge()
    }

    /**
     * <code>int32 id = 3;</code>
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>int32 id = 3;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun usermgmt.Usermgmt.User.copy(block: usermgmt.UserKt.Dsl.() -> kotlin.Unit): usermgmt.Usermgmt.User =
  usermgmt.UserKt.Dsl._create(this.toBuilder()).apply { block() }._build()
