//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: usermgmt/usermgmt.proto

package usermgmt;

@kotlin.jvm.JvmSynthetic
public inline fun usersList(block: usermgmt.UsersListKt.Dsl.() -> kotlin.Unit): usermgmt.Usermgmt.UsersList =
  usermgmt.UsersListKt.Dsl._create(usermgmt.Usermgmt.UsersList.newBuilder()).apply { block() }._build()
public object UsersListKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: usermgmt.Usermgmt.UsersList.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: usermgmt.Usermgmt.UsersList.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): usermgmt.Usermgmt.UsersList = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UsersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .usermgmt.User users = 1;</code>
     */
     public val users: com.google.protobuf.kotlin.DslList<usermgmt.Usermgmt.User, UsersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getUsersList()
      )
    /**
     * <code>repeated .usermgmt.User users = 1;</code>
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addUsers")
    public fun com.google.protobuf.kotlin.DslList<usermgmt.Usermgmt.User, UsersProxy>.add(value: usermgmt.Usermgmt.User) {
      _builder.addUsers(value)
    }/**
     * <code>repeated .usermgmt.User users = 1;</code>
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<usermgmt.Usermgmt.User, UsersProxy>.plusAssign(value: usermgmt.Usermgmt.User) {
      add(value)
    }/**
     * <code>repeated .usermgmt.User users = 1;</code>
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllUsers")
    public fun com.google.protobuf.kotlin.DslList<usermgmt.Usermgmt.User, UsersProxy>.addAll(values: kotlin.collections.Iterable<usermgmt.Usermgmt.User>) {
      _builder.addAllUsers(values)
    }/**
     * <code>repeated .usermgmt.User users = 1;</code>
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<usermgmt.Usermgmt.User, UsersProxy>.plusAssign(values: kotlin.collections.Iterable<usermgmt.Usermgmt.User>) {
      addAll(values)
    }/**
     * <code>repeated .usermgmt.User users = 1;</code>
     * @param index The index to set the value at.
     * @param value The users to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setUsers")
    public operator fun com.google.protobuf.kotlin.DslList<usermgmt.Usermgmt.User, UsersProxy>.set(index: kotlin.Int, value: usermgmt.Usermgmt.User) {
      _builder.setUsers(index, value)
    }/**
     * <code>repeated .usermgmt.User users = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearUsers")
    public fun com.google.protobuf.kotlin.DslList<usermgmt.Usermgmt.User, UsersProxy>.clear() {
      _builder.clearUsers()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun usermgmt.Usermgmt.UsersList.copy(block: usermgmt.UsersListKt.Dsl.() -> kotlin.Unit): usermgmt.Usermgmt.UsersList =
  usermgmt.UsersListKt.Dsl._create(this.toBuilder()).apply { block() }._build()
